# Generated by Django 5.2.7 on 2025-11-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Search", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="document",
            name="rubrics",
            field=models.TextField(verbose_name="Рубрики"),
        ),
        migrations.AlterField(
            model_name="document",
            name="text",
            field=models.TextField(verbose_name="Текст документа"),
        ),
    ]
